### ISSUE TITLE
Nautilus not applying the theme correctly (manual installation)

### ISSUE THREAD

**Issue by lactua** [rose-pine/gtk#35] opened 2024-08-24 21:02 UTC
![24-08-2024-23-02-16](https://github.com/user-attachments/assets/77ca5c5f-e295-4fb0-b75e-66595ba880e4)

**Comment by lactua** [comment] 2024-08-24 21:03
Here is my .config/gtk-4.0/settings.ini

[Settings
gtk-application-prefer-dark-theme=1
gtk-cursor-theme-name=Afterglow-cursors
gtk-icon-theme-name=Papirus-Dark

**Comment by ThatOneCalculator** [comment] 2024-08-24 21:28
Duplicate of #30

**Closed as not planned by ThatOneCalculator** 2024-08-24 21:28 UTC

**Comment by lactua** [comment] 2024-08-25 22:25
I don't really understand how this is a duplicate. I took a look to the issue you mentionned and our problem isn't really the same as his is about gtk3. However I tried the solution mentionned in the issue and it didn't fix the problem I still have a white bar in nautilus

**Comment by Hamza-Rafi** [comment] 2024-12-24 07:00
I have also come across the exact same problem
![image](https://github.com/user-attachments/assets/57f127ef-17d2-40cb-9c36-164f8e97fa49)

This is my `.config/gtk-4.0/settings.ini`:
```
[Settings]
gtk-application-prefer-dark-theme=0
```
